/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * BACKWARD-COMPAT SHIM — auto-generated by scripts/create-default-service-shim.mjs
 * Lazily calls underlying service implementations to avoid import-time
 * side-effects. This makes the module safe to import in test runners and
 * environments where generated service modules may perform runtime work.
 *
 * Do not edit manually — re-run `npm run generate:client` to regenerate.
 */

type MethodFn = (...args: any[]) => Promise<any>

const serviceLoaders = {
  ApiariesService: () => import('./ApiariesService'),
  AuthService: () => import('./AuthService'),
  BestandsbuchService: () => import('./BestandsbuchService'),
  HivesService: () => import('./HivesService'),
  InspectionsService: () => import('./InspectionsService'),
  QueensService: () => import('./QueensService'),
  TreatmentAgentsService: () => import('./TreatmentAgentsService'),
  UsersService: () => import('./UsersService'),
};

function makeLazyMethod(loader: () => Promise<any>, exportName: string, methodName: string): MethodFn {
  return async (...args: any[]) => {
    const mod = await loader()
    const svc = mod[exportName] ?? mod.default ?? mod
    const fn = svc?.[methodName]
    if (typeof fn !== 'function') {
      throw new Error(methodName + ' is not available on ' + exportName)
    }
    return fn.apply(svc, args)
  }
}

const DefaultService: Record<string, MethodFn> = {
  // ── Apiaries ----------------------------------------------------
  getApiV1Apiaries: makeLazyMethod(serviceLoaders.ApiariesService, 'ApiariesService', 'getApiV1Apiaries'),
  postApiV1Apiaries: makeLazyMethod(serviceLoaders.ApiariesService, 'ApiariesService', 'postApiV1Apiaries'),
  getApiV1Apiaries1: makeLazyMethod(serviceLoaders.ApiariesService, 'ApiariesService', 'getApiV1Apiaries1'),
  putApiV1Apiaries: makeLazyMethod(serviceLoaders.ApiariesService, 'ApiariesService', 'putApiV1Apiaries'),
  deleteApiV1Apiaries: makeLazyMethod(serviceLoaders.ApiariesService, 'ApiariesService', 'deleteApiV1Apiaries'),

  // ── Auth --------------------------------------------------------
  postApiV1AuthRegister: makeLazyMethod(serviceLoaders.AuthService, 'AuthService', 'postApiV1AuthRegister'),
  postApiV1AuthLogin: makeLazyMethod(serviceLoaders.AuthService, 'AuthService', 'postApiV1AuthLogin'),
  postApiV1AuthRefresh: makeLazyMethod(serviceLoaders.AuthService, 'AuthService', 'postApiV1AuthRefresh'),
  postApiV1AuthLogout: makeLazyMethod(serviceLoaders.AuthService, 'AuthService', 'postApiV1AuthLogout'),
  postApiV1AuthForgotPassword: makeLazyMethod(serviceLoaders.AuthService, 'AuthService', 'postApiV1AuthForgotPassword'),
  postApiV1AuthResetPassword: makeLazyMethod(serviceLoaders.AuthService, 'AuthService', 'postApiV1AuthResetPassword'),
  getApiV1AuthVerifyEmail: makeLazyMethod(serviceLoaders.AuthService, 'AuthService', 'getApiV1AuthVerifyEmail'),

  // ── Bestandsbuch ------------------------------------------------
  getApiV1Bestandsbuch: makeLazyMethod(serviceLoaders.BestandsbuchService, 'BestandsbuchService', 'getApiV1Bestandsbuch'),
  postApiV1Bestandsbuch: makeLazyMethod(serviceLoaders.BestandsbuchService, 'BestandsbuchService', 'postApiV1Bestandsbuch'),
  getApiV1BestandsbuchYears: makeLazyMethod(serviceLoaders.BestandsbuchService, 'BestandsbuchService', 'getApiV1BestandsbuchYears'),
  putApiV1Bestandsbuch: makeLazyMethod(serviceLoaders.BestandsbuchService, 'BestandsbuchService', 'putApiV1Bestandsbuch'),
  deleteApiV1Bestandsbuch: makeLazyMethod(serviceLoaders.BestandsbuchService, 'BestandsbuchService', 'deleteApiV1Bestandsbuch'),

  // ── Hives -------------------------------------------------------
  getApiV1Hives: makeLazyMethod(serviceLoaders.HivesService, 'HivesService', 'getApiV1Hives'),
  postApiV1Hives: makeLazyMethod(serviceLoaders.HivesService, 'HivesService', 'postApiV1Hives'),
  getApiV1Hives1: makeLazyMethod(serviceLoaders.HivesService, 'HivesService', 'getApiV1Hives1'),
  putApiV1Hives: makeLazyMethod(serviceLoaders.HivesService, 'HivesService', 'putApiV1Hives'),
  deleteApiV1Hives: makeLazyMethod(serviceLoaders.HivesService, 'HivesService', 'deleteApiV1Hives'),

  // ── Inspections -------------------------------------------------
  getApiV1Inspections: makeLazyMethod(serviceLoaders.InspectionsService, 'InspectionsService', 'getApiV1Inspections'),
  postApiV1Inspections: makeLazyMethod(serviceLoaders.InspectionsService, 'InspectionsService', 'postApiV1Inspections'),
  putApiV1Inspections: makeLazyMethod(serviceLoaders.InspectionsService, 'InspectionsService', 'putApiV1Inspections'),
  deleteApiV1Inspections: makeLazyMethod(serviceLoaders.InspectionsService, 'InspectionsService', 'deleteApiV1Inspections'),

  // ── Queens ------------------------------------------------------
  getApiV1Queens: makeLazyMethod(serviceLoaders.QueensService, 'QueensService', 'getApiV1Queens'),
  postApiV1Queens: makeLazyMethod(serviceLoaders.QueensService, 'QueensService', 'postApiV1Queens'),
  getApiV1Queens1: makeLazyMethod(serviceLoaders.QueensService, 'QueensService', 'getApiV1Queens1'),
  putApiV1Queens: makeLazyMethod(serviceLoaders.QueensService, 'QueensService', 'putApiV1Queens'),
  deleteApiV1Queens: makeLazyMethod(serviceLoaders.QueensService, 'QueensService', 'deleteApiV1Queens'),
  postApiV1QueensAssign: makeLazyMethod(serviceLoaders.QueensService, 'QueensService', 'postApiV1QueensAssign'),
  postApiV1QueensRemoveFromHive: makeLazyMethod(serviceLoaders.QueensService, 'QueensService', 'postApiV1QueensRemoveFromHive'),

  // ── TreatmentAgents ---------------------------------------------
  getApiV1TreatmentAgents: makeLazyMethod(serviceLoaders.TreatmentAgentsService, 'TreatmentAgentsService', 'getApiV1TreatmentAgents'),
  postApiV1TreatmentAgents: makeLazyMethod(serviceLoaders.TreatmentAgentsService, 'TreatmentAgentsService', 'postApiV1TreatmentAgents'),

  // ── Users -------------------------------------------------------
  getApiV1UsersMe: makeLazyMethod(serviceLoaders.UsersService, 'UsersService', 'getApiV1UsersMe'),
  putApiV1UsersMe: makeLazyMethod(serviceLoaders.UsersService, 'UsersService', 'putApiV1UsersMe'),
};

// Backwards-compat: some consumers import the module and expect a
// `DefaultService` property on it (old shim). Provide it.
;(DefaultService as any).DefaultService = DefaultService

export { DefaultService }
export default DefaultService
