/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * BACKWARD-COMPAT SHIM — auto-generated by scripts/create-default-service-shim.mjs
 * Combines all tag-based services into a single DefaultService namespace.
 * Do not edit manually — re-run `npm run generate:client` to regenerate.
 */

import { ApiariesService } from './ApiariesService';
import { AuthService } from './AuthService';
import { HivesService } from './HivesService';
import { InspectionsService } from './InspectionsService';
import { QueensService } from './QueensService';
import { TreatmentAgentsService } from './TreatmentAgentsService';
import { UsersService } from './UsersService';

export const DefaultService = {
  // ── Apiaries ────────────────────────────────────────────────────
  getApiV1Apiaries: ApiariesService.getApiV1Apiaries,
  postApiV1Apiaries: ApiariesService.postApiV1Apiaries,
  getApiV1Apiaries1: ApiariesService.getApiV1Apiaries1,
  putApiV1Apiaries: ApiariesService.putApiV1Apiaries,
  deleteApiV1Apiaries: ApiariesService.deleteApiV1Apiaries,

  // ── Auth ────────────────────────────────────────────────────────
  postApiV1AuthRegister: AuthService.postApiV1AuthRegister,
  postApiV1AuthLogin: AuthService.postApiV1AuthLogin,
  postApiV1AuthRefresh: AuthService.postApiV1AuthRefresh,
  postApiV1AuthLogout: AuthService.postApiV1AuthLogout,
  postApiV1AuthForgotPassword: AuthService.postApiV1AuthForgotPassword,
  postApiV1AuthResetPassword: AuthService.postApiV1AuthResetPassword,
  getApiV1AuthVerifyEmail: AuthService.getApiV1AuthVerifyEmail,

  // ── Hives ───────────────────────────────────────────────────────
  getApiV1Hives: HivesService.getApiV1Hives,
  postApiV1Hives: HivesService.postApiV1Hives,
  getApiV1Hives1: HivesService.getApiV1Hives1,
  putApiV1Hives: HivesService.putApiV1Hives,
  deleteApiV1Hives: HivesService.deleteApiV1Hives,

  // ── Inspections ─────────────────────────────────────────────────
  getApiV1Inspections: InspectionsService.getApiV1Inspections,
  postApiV1Inspections: InspectionsService.postApiV1Inspections,
  putApiV1Inspections: InspectionsService.putApiV1Inspections,
  deleteApiV1Inspections: InspectionsService.deleteApiV1Inspections,

  // ── Queens ──────────────────────────────────────────────────────
  getApiV1Queens: QueensService.getApiV1Queens,
  postApiV1Queens: QueensService.postApiV1Queens,
  getApiV1Queens1: QueensService.getApiV1Queens1,
  putApiV1Queens: QueensService.putApiV1Queens,
  deleteApiV1Queens: QueensService.deleteApiV1Queens,
  postApiV1QueensAssign: QueensService.postApiV1QueensAssign,
  postApiV1QueensRemoveFromHive: QueensService.postApiV1QueensRemoveFromHive,

  // ── TreatmentAgents ─────────────────────────────────────────────
  getApiV1TreatmentAgents: TreatmentAgentsService.getApiV1TreatmentAgents,
  postApiV1TreatmentAgents: TreatmentAgentsService.postApiV1TreatmentAgents,

  // ── Users ───────────────────────────────────────────────────────
  getApiV1UsersMe: UsersService.getApiV1UsersMe,
  putApiV1UsersMe: UsersService.putApiV1UsersMe,
};
