/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * BACKWARD-COMPAT SHIM — auto-generated by scripts/create-default-service-shim.mjs
 * Lazily calls underlying service implementations to avoid import-time
 * side-effects. This makes the module safe to import in test runners and
 * environments where generated service modules may perform runtime work.
 *
 * Do not edit manually — re-run `npm run generate:client` to regenerate.
 */

type MethodFn = (...args: any[]) => Promise<any>

function makeLazyMethod(modulePath: string, exportName: string, methodName: string): MethodFn {
  return async (...args: any[]) => {
    const mod = await import(modulePath)
    const svc = mod[exportName] ?? mod.default ?? mod
    const fn = svc?.[methodName]
    if (typeof fn !== 'function') {
      throw new Error(methodName + ' is not available on ' + modulePath)
    }
    return fn.apply(svc, args)
  }
}

const DefaultService: Record<string, MethodFn> = {
  // ── Apiaries ----------------------------------------------------
  getApiV1Apiaries: makeLazyMethod('./ApiariesService', 'ApiariesService', 'getApiV1Apiaries'),
  postApiV1Apiaries: makeLazyMethod('./ApiariesService', 'ApiariesService', 'postApiV1Apiaries'),
  getApiV1Apiaries1: makeLazyMethod('./ApiariesService', 'ApiariesService', 'getApiV1Apiaries1'),
  putApiV1Apiaries: makeLazyMethod('./ApiariesService', 'ApiariesService', 'putApiV1Apiaries'),
  deleteApiV1Apiaries: makeLazyMethod('./ApiariesService', 'ApiariesService', 'deleteApiV1Apiaries'),

  // ── Auth --------------------------------------------------------
  postApiV1AuthRegister: makeLazyMethod('./AuthService', 'AuthService', 'postApiV1AuthRegister'),
  postApiV1AuthLogin: makeLazyMethod('./AuthService', 'AuthService', 'postApiV1AuthLogin'),
  postApiV1AuthRefresh: makeLazyMethod('./AuthService', 'AuthService', 'postApiV1AuthRefresh'),
  postApiV1AuthLogout: makeLazyMethod('./AuthService', 'AuthService', 'postApiV1AuthLogout'),
  postApiV1AuthForgotPassword: makeLazyMethod('./AuthService', 'AuthService', 'postApiV1AuthForgotPassword'),
  postApiV1AuthResetPassword: makeLazyMethod('./AuthService', 'AuthService', 'postApiV1AuthResetPassword'),
  getApiV1AuthVerifyEmail: makeLazyMethod('./AuthService', 'AuthService', 'getApiV1AuthVerifyEmail'),

  // ── Hives -------------------------------------------------------
  getApiV1Hives: makeLazyMethod('./HivesService', 'HivesService', 'getApiV1Hives'),
  postApiV1Hives: makeLazyMethod('./HivesService', 'HivesService', 'postApiV1Hives'),
  getApiV1Hives1: makeLazyMethod('./HivesService', 'HivesService', 'getApiV1Hives1'),
  putApiV1Hives: makeLazyMethod('./HivesService', 'HivesService', 'putApiV1Hives'),
  deleteApiV1Hives: makeLazyMethod('./HivesService', 'HivesService', 'deleteApiV1Hives'),

  // ── Inspections -------------------------------------------------
  getApiV1Inspections: makeLazyMethod('./InspectionsService', 'InspectionsService', 'getApiV1Inspections'),
  postApiV1Inspections: makeLazyMethod('./InspectionsService', 'InspectionsService', 'postApiV1Inspections'),
  putApiV1Inspections: makeLazyMethod('./InspectionsService', 'InspectionsService', 'putApiV1Inspections'),
  deleteApiV1Inspections: makeLazyMethod('./InspectionsService', 'InspectionsService', 'deleteApiV1Inspections'),

  // ── Queens ------------------------------------------------------
  getApiV1Queens: makeLazyMethod('./QueensService', 'QueensService', 'getApiV1Queens'),
  postApiV1Queens: makeLazyMethod('./QueensService', 'QueensService', 'postApiV1Queens'),
  getApiV1Queens1: makeLazyMethod('./QueensService', 'QueensService', 'getApiV1Queens1'),
  putApiV1Queens: makeLazyMethod('./QueensService', 'QueensService', 'putApiV1Queens'),
  deleteApiV1Queens: makeLazyMethod('./QueensService', 'QueensService', 'deleteApiV1Queens'),
  postApiV1QueensAssign: makeLazyMethod('./QueensService', 'QueensService', 'postApiV1QueensAssign'),
  postApiV1QueensRemoveFromHive: makeLazyMethod('./QueensService', 'QueensService', 'postApiV1QueensRemoveFromHive'),

  // ── TreatmentAgents ---------------------------------------------
  getApiV1TreatmentAgents: makeLazyMethod('./TreatmentAgentsService', 'TreatmentAgentsService', 'getApiV1TreatmentAgents'),
  postApiV1TreatmentAgents: makeLazyMethod('./TreatmentAgentsService', 'TreatmentAgentsService', 'postApiV1TreatmentAgents'),

  // ── Users -------------------------------------------------------
  getApiV1UsersMe: makeLazyMethod('./UsersService', 'UsersService', 'getApiV1UsersMe'),
  putApiV1UsersMe: makeLazyMethod('./UsersService', 'UsersService', 'putApiV1UsersMe'),
}

// Backwards-compat: some consumers import the module and expect a
// `DefaultService` property on it (old shim). Provide it.
(DefaultService as any).DefaultService = DefaultService

export { DefaultService }
export default DefaultService
